sudo: false

language: c

cache:
  directories:
    - ~/.stack

before_install:
  - apt-get install gmp
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - curl -L https://www.stackage.org/stack/linux-x86_64 | 
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps
  - stack exec stack-example-exe

post_script:
  - ls ~/.stack
  - ls ~/.ghc
  - ls ~/.cabal
