sudo: false

language: c

cache:
  directories:
    - ~/.stack

addons:
  apt:
    packages:
      - ghc-7.10.3
    sources:
      - hvr-ghc

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.3/bin:$PATH

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps
  - stack exec stack-example-exe
